name: Android Build
on:
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.2

      - name: Restore Others Caches
        uses: actions/cache@v4
        with:
          key: cache-haxe-hxcpp-gradle-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            cache-haxe-hxcpp-gradle-${{ runner.os }}-
          path: |
            .haxelib/
            ~/.hxcpp/
            ~/.gradle/

      - name: Restore Project Cache
        uses: actions/cache@v4
        with:
          key: cache-android-obj-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            cache-android-obj-${{ runner.os }}-
          path: |
            export/release/android/haxe/
            export/release/android/obj/

      - name: Setup HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=$HOME/.hxcpp" >> $GITHUB_ENV

      - name: Install and update libraries
        run: haxe -cp commandline -D analyzer-optimize --run Main setup -s

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Configure Android environment
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Build Android
        run: haxelib run lime build android -final

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NeuroEngine-release
          path: export/release/android/bin/app/build/outputs/apk/release/*.apk

      - name: Upload Others Cache
        uses: actions/cache@v4.2.3
        with:
          key: cache-haxe-hxcpp-gradle-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          path: |
            .haxelib/
            ~/.hxcpp/
            ~/.gradle/

      - name: Upload project object cache
        uses: actions/cache@v4.2.3
        with:
          key: cache-android-obj-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          path: |
            export/release/android/haxe/
            export/release/android/obj/
