name: Android Build

on:
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Haxe / HXCPP / Gradle cache
        uses: actions/cache@v4
        with:
          key: cache-haxe-hxcpp-gradle-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            cache-haxe-hxcpp-gradle-${{ runner.os }}-
          path: |
            .haxelib/
            ~/.hxcpp/
            ~/.gradle/

      - name: Restore Android object cache
        uses: actions/cache@v4
        with:
          key: cache-android-obj-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            cache-android-obj-${{ runner.os }}-
          path: |
            export/release/android/haxe/
            export/release/android/obj/

      - name: Setup HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=$HOME/.hxcpp" >> $GITHUB_ENV

      - name: Setup Haxelib dependencies
        run: |
          haxelib setup ~/haxelib

          haxelib install lime 8.1.2 --quiet
          haxelib install openfl 9.3.3 --quiet
          haxelib install flixel 5.6.1 --quiet
          haxelib install flixel-addons 3.2.2 --quiet
          haxelib install flixel-ui 2.6.1 --quiet
          haxelib install tjson 1.4.0 --quiet
          haxelib install format 3.7.0 --quiet
          haxelib install hxp 1.3.0 --quiet
          haxelib install hxcpp 4.3.2 --quiet
          haxelib install SScript 8.1.6 --quiet
          haxelib install hscript-iris 1.1.3 --quiet

          haxelib git hxluajit https://github.com/MAJigsaw77/hxluajit
          haxelib git hxvlc https://github.com/MAJigsaw77/hxvlc
          haxelib git linc_luajit https://github.com/superpowers04/linc_luajit
          haxelib git hxdiscord_rpc https://github.com/MAJigsaw77/hxdiscord_rpc
          haxelib git flxanimate https://github.com/MaybeMaru/flixel-animate
          haxelib git hxgamemode https://github.com/MAJigsaw77/hxgamemode
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Android environment
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Setup KeyStore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > key.keystore

      - name: Build Android release
        run: |
          haxelib run lime build android -final \
            -keystore key.keystore \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keyalias "${{ secrets.KEY_ALIAS }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PeachEngine-Android
          path: export/release/android/bin/PeachEngine-release.apk

      - name: Save Haxe / HXCPP / Gradle cache
        uses: actions/cache@v4
        with:
          key: cache-haxe-hxcpp-gradle-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          path: |
            .haxelib/
            ~/.hxcpp/
            ~/.gradle/

      - name: Save Android object cache
        uses: actions/cache@v4
        with:
          key: cache-android-obj-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          path: |
            export/release/android/haxe/
            export/release/android/obj/
