name: Android Build
on:
  push:
    branches: ['main']
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: Android Build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false
          fetch-depth: 0

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v2
        with:
          haxe-version: 4.3.7

      - name: Restore Haxe/HXCPP/Gradle cache
        uses: actions/cache@v4
        with:
          key: cache-haxe-hxcpp-gradle-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            cache-haxe-hxcpp-gradle-${{ runner.os }}-
          path: |
            .haxelib/
            ~/.hxcpp/
            ~/.gradle/

      - name: Restore project object cache
        uses: actions/cache@v4
        with:
          key: cache-android-obj-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          restore-keys: |
            cache-android-obj-${{ runner.os }}-
          path: |
            export/release/android/haxe/
            export/release/android/obj/

      - name: Setup HXCPP compile cache
        run: echo "HXCPP_COMPILE_CACHE=$HOME/.hxcpp" >> $GITHUB_ENV

      - name: Install Haxe libraries
        run: |
          haxelib git hmm https://github.com/FNF-SE/hmm --skip-dependencies --quiet
          haxelib run hmm install --quiet

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Configure Android environment
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME
          haxelib run lime config ANDROID_SETUP true

      - name: Setup KeyStore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > key.keystore

      - name: Rebuild essential git libs for Android
        run: |
          haxelib run lime rebuild flxanimate -Dandroid
          haxelib run lime rebuild hxdiscord_rpc -Dandroid
          haxelib run lime rebuild hxluajit -Dandroid
          haxelib run lime rebuild linc_luajit -Dandroid
            
      - name: Build Android release
        run: |
          haxelib run lime build android -final -Dandroid
            -final \
            -keystore key.keystore \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keyalias "${{ secrets.KEY_ALIAS }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PeachEngine-Android
          path: export/release/android/bin/PeachEngine-release.apk

      - name: Save Haxe/HXCPP/Gradle cache
        uses: actions/cache@v4.2.3
        with:
          key: cache-haxe-hxcpp-gradle-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          path: |
            .haxelib/
            ~/.hxcpp/
            ~/.gradle/

      - name: Save project object cache
        uses: actions/cache@v4.2.3
        with:
          key: cache-android-obj-${{ runner.os }}-${{ hashFiles('**/haxelib.json') }}
          path: |
            export/release/android/haxe/
            export/release/android/obj/
